# Generated by Django 6.0.2 on 2026-04-01 17:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("nif", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=64)),
                ("fidelity", models.IntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=128)),
                ("contact", models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Distributor",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False
                    ),
                ),
                ("contact", models.CharField(blank=True, max_length=64, null=True)),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("prodid", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("brand", models.CharField(max_length=64)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("req_cold", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "sname",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("department", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("orderid", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "ord_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("ord_date", models.DateField()),
                (
                    "distributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.distributor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderContainsProd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_qty",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.product"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                through="app.OrderContainsProd", to="app.product"
            ),
        ),
        migrations.CreateModel(
            name="ProductIVA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iva",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                ("purchid", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchContainsProd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purch_qty",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.product"
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.purchase"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="purchase",
            name="products",
            field=models.ManyToManyField(
                through="app.PurchContainsProd", to="app.product"
            ),
        ),
        migrations.CreateModel(
            name="PurchPayMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pay_method", models.CharField(max_length=32)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.purchase"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="section_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.section"
            ),
        ),
        migrations.CreateModel(
            name="Supermarket",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("location", models.CharField(max_length=128)),
                ("opening_time", models.TimeField()),
                ("close_time", models.TimeField()),
                ("sections", models.ManyToManyField(to="app.section")),
            ],
        ),
        migrations.AddField(
            model_name="purchase",
            name="supermarket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.supermarket"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="supermarket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.supermarket"
            ),
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("enumber", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64)),
                ("role", models.CharField(max_length=32)),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(16)]
                    ),
                ),
                ("contact", models.CharField(max_length=64)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="app.employee",
                    ),
                ),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.supermarket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                ("wnumber", models.IntegerField(primary_key=True, serialize=False)),
                ("area", models.CharField(max_length=64)),
                (
                    "supermarket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.supermarket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WareHStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wqty",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.product"
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.warehouse"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="warehouse",
            name="products",
            field=models.ManyToManyField(through="app.WareHStock", to="app.product"),
        ),
    ]
